apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 3
  selector:
    app: os1
  template:
    metadata:
      name: mypod
      labels:
        app: os1
    spec:
      containers:
      - name: myc1
        image: vimal13/apache-webserver-php
